modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
side = "CLIENT"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}_geckolib.mixins.json"
requiredMods = ["geckolib"]

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "geckolib"
type = "optional"
versionRange = "[4.9,)"
ordering = "AFTER"
side = "CLIENT"
